// Blog
export const BLOG_NEXT_PATH_SET = 'BLOG_NEXT_PATH_SET';
export const BLOG_POSTS_ERROR_CLEAR = 'BLOG_POSTS_ERROR_CLEAR';
export const BLOG_POSTS_ERROR_SET = 'BLOG_POSTS_ERROR_SET';
export const BLOG_POSTS_FETCH = 'BLOG_POSTS_FETCH';
export const BLOG_POSTS_RECEIVE = 'BLOG_POSTS_RECEIVE';
export const BLOG_PREVIOUS_PATH_SET = 'BLOG_PREVIOUS_PATH_SET';
export const BLOG_SET_ACTIVE_POST = 'BLOG_SET_ACTIVE_POST';
export const BLOG_SET_ACTIVE_POST_SLUG = 'BLOG_SET_ACTIVE_POST_SLUG';
export const BLOG_SET_DEFAULT_POST = 'BLOG_SET_DEFAULT_POST';

// Contact
export const CONTACT_FORM_SUBMIT = 'CONTACT_FORM_SUBMIT';

// Projects
export const PROJECTS_NEXT_PATH_SET = 'PROJECTS_NEXT_PATH_SET';
export const PROJECTS_ERROR_CLEAR = 'PROJECTS_ERROR_CLEAR';
export const PROJECTS_ERROR_SET = 'PROJECTS_ERROR_SET';
export const PROJECTS_FETCH = 'PROJECTS_FETCH';
export const PROJECTS_PREVIOUS_PATH_SET = 'PROJECTS_PREVIOUS_PATH_SET';
export const PROJECTS_RECEIVE = 'PROJECTS_RECEIVE';
export const PROJECTS_SET_ACTIVE = 'PROJECTS_SET_ACTIVE';
export const PROJECTS_SET_ACTIVE_SLUG = 'PROJECTS_SET_ACTIVE_SLUG';
export const PROJECTS_SET_DEFAULT = 'PROJECTS_SET_DEFAULT';
