// Blog
export const BLOG_POSTS_FETCH = 'BLOG_POSTS_FETCH';
export const BLOG_POSTS_RECEIVE = 'BLOG_POSTS_RECEIVE';
export const BLOG_SET_ACTIVE_POST = 'BLOG_SET_ACTIVE_POST';
export const BLOG_SET_ACTIVE_POST_SLUG = 'BLOG_SET_ACTIVE_POST_SLUG';

// Projects
export const PROJECTS_FETCH = 'PROJECTS_FETCH';
export const PROJECTS_RECEIVE = 'PROJECTS_RECEIVE';
