// Blog
export const BLOG_POSTS_ERROR_CLEAR = 'BLOG_POSTS_ERROR_CLEAR';
export const BLOG_POSTS_ERROR_SET = 'BLOG_POSTS_ERROR_SET';
export const BLOG_POSTS_FETCH = 'BLOG_POSTS_FETCH';
export const BLOG_POSTS_RECEIVE = 'BLOG_POSTS_RECEIVE';
export const BLOG_SET_ACTIVE_POST = 'BLOG_SET_ACTIVE_POST';
export const BLOG_SET_ACTIVE_POST_SLUG = 'BLOG_SET_ACTIVE_POST_SLUG';

// Projects
export const PROJECTS_ERROR_CLEAR = 'PROJECTS_ERROR_CLEAR';
export const PROJECTS_ERROR_SET = 'PROJECTS_ERROR_SET';
export const PROJECTS_FETCH = 'PROJECTS_FETCH';
export const PROJECTS_RECEIVE = 'PROJECTS_RECEIVE';
export const PROJECTS_SET_ACTIVE = 'PROJECTS_SET_ACTIVE';
export const PROJECTS_SET_ACTIVE_SLUG = 'PROJECTS_SET_ACTIVE_SLUG';

// Routing
export const ROUTING_SET_NEXT_CONTENT_PATH = 'ROUTING_SET_NEXT_CONTENT_PATH';
export const ROUTING_SET_PREVIOUS_CONTENT_PATH = 'ROUTING_SET_PREVIOUS_CONTENT_PATH';
